### PR TITLE
Workaround for undiscovered dependencies in external libraries

### LINKED ISSUE #3: Object instead of string error during production mode
This is a brief write up the issue we came across on Friday.

Currently, there is a bug in Magento 2 production mode which results in dependencies on external libraries to not be instantiated correctly.

This results in the following error:

    [2016-12-09 11:26:30] main.CRITICAL: Warning: file_exists() expects parameter 1 to be a valid path, object given in /Users/ashsmith/Sites/magento2-environment/magento/vendor/meanbee/royalmail-php-library/src/Data.php on line 356 [] []

In our case, ObjectManager was being provided as the default argument. When we actually expected to be able to instantiate the object without any arguments.

Defining in `di.xml` does not work.

We have found the issue reported here: https://github.com/magento/magento2/issues/6739

The agreed solution internally is to instantiate the class in question ourselves, until this issue is resolved by Magento.

### PR DESCRIPTION
**Pull request by ashsmith**
This fixes #3.

The workaround implements a getter/setter for the external Carrier class. Which by default will instantiate the class itself, rather than using Magento's DI.

### CODE REVIEW

**Comment by punkstar** [comment]
References https://github.com/magento/magento2/issues/6739.

File: src/Model/Carrier.php [hunk 1]
```diff
@@ -79,8 +79,6 @@ public function __construct(
         $this->rateResultFactory = $rateResultFactory;
         $this->rateMethodFactory = $rateMethodFactory;
         $this->rounder = $rounder;
-        $this->carrier = $carrier;
```
Comment (punkstar) [inline src/Model/Carrier.php:82]: Can remove the argument in the constructor too, seeing as we're not doing anything with it.

**Review by punkstar — CHANGES_REQUESTED** [review]
Constructor update required.

**Review by punkstar — APPROVED** [review]
